<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../form/NewForm.vue'
export default {

    props: ['id'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Offer Manager",
                formName : "OfferForm",
                model : "Offer",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'display', val : 'Display', type : 'text' },
                    { key : 'offer_name', val : 'Offer Name', type : 'text' },
                    { key : 'coupon_code', val : 'Coupon', type : 'text' },
                    { key : 'start', val : 'Start', type : 'text' },
                    { key : 'end', val : 'End', type : 'text' },
                    { key : 'offer_type', val : 'Offer Type', type : 'text' },
                    { key : 'offer_for', val : 'Offer For', type : 'text' },
                    { key : 'minimum_purchase_amount', val : 'Min Purchase', type : 'text' },
                    { key : 'maximum_offer_amount', val : 'Max Offer', type : 'text' },
                    { key : 'offer_value', val : 'Offer', type : 'text' },
                    { key : 'ticket_size', val : 'Size', type : 'text' },
                    { key : 'ticket_per_day', val : 'Day', type : 'text' },
                    { key : 'ticket_per_customer', val : 'Cust', type : 'text' },
                    { key : 'ticket_per_customer_per_day', val : 'Day Cust', type : 'text' },   
                    { key : 'media', val : 'Media', type : 'image' },
                ],
                elements : [
                    {
                        label : 'Display',
                        name : 'display',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Display', value : '' },
                            { key : 'Show', value : 'Show' },
                            { key : 'Hide', value : 'Hide' },
                        ],
                        placeholder : 'Please Select Display',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Select Display',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Offer Name',
                        name : 'offer_name',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Offer Name',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Offer Name',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Coupon Code',
                        name : 'coupon_code',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Coupon Code',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Coupon Code',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Minimum Purchase Amount',
                        name : 'minimum_purchase_amount',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Minimum Purchase Amount',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Minimum Purchase Amount',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Maximum Offer Amount',
                        name : 'maximum_offer_amount',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Maximum Offer Amount',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Maximum Offer Amount',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Offer Value',
                        name : 'offer_value',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Offer Value',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Offer Value',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Description',
                        name : 'description',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Description',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Description',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Start',
                        name : 'start',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Start',
                        type : 'date',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Start',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'End',
                        name : 'end',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter End',
                        type : 'date',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter End',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Offer Type',
                        name : 'offer_type',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Offer Type', value : '' },
                            { key : 'Flat Discount', value : 'Flat Discount' },
                            { key : 'Percentile Discount', value : 'Percentile Discount' },
                        ],
                        placeholder : 'Please Select Offer Type',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Offer Type',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Offer For',
                        name : 'offer_for',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Offer For', value : '' },
                            { key : 'All Orders', value : 'All Orders' },
                            { key : 'First Order', value : 'First Order' },
                        ],
                        placeholder : 'Please Select Offer For',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Select Offer For',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    

                    {
                        label : 'Ticket Size',
                        name : 'ticket_size',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Ticket Size',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Ticket Size',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Tickets Per Day',
                        name : 'ticket_per_day',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Tickets Per Day',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Tickets Per Day',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Tickets Per Customer',
                        name : 'ticket_per_customer',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Tickets Per Customer',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Tickets Per Customer',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Tickets Per Custmer Per Day',
                        name : 'ticket_per_customer_per_day',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Tickets Per Custmer Per Day',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Tickets Per Custmer Per Day',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Offer Media',
                        name : 'media',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Offer Media',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Offer Media is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },



                ],
            },
        }
    },

    methods : {

        change(e){
            /* console.log(e.target.value); */
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
    },

    mounted() {
    },

}
</script>
