<template>
    <div class="container-fluid p-0">
        <lits-form :formData="formData" @OnChange="change($event)" @OnEdit="edit($event)"></lits-form>
    </div>
</template>

<script>
import LitsForm from '../../form/NewForm.vue'
export default {

    props: ['id', 'product_group'],

    components: {
        LitsForm,
    },

    data: function (){
        return {
            formData : {
                id : 0,
                title : "Product Manager",
                formName : "ProductForm",
                model : "Product",
                action : "CRUD", /* CRUD | EDIT | SEARCH */
                method : "",
                custom_query : [],
                with : [],
                mail : {
                    name : "Sandeep Rathod",
                    to : "sandeep198558@yahoo.com",
                    subject : "Email From Users of Zataks",
                },
                settings : {
                    isTitle : true,
                    isReset : true,
                    isSubmit : true,
                    isDateSearch : false,
                    isExport : true,

                    isForm : true,
                    isSearch : true,
                    isResults : true,
                    isAction : true,
                    isLoadMore : true,
                },
                display : [
                    { key : 'data_category', val : 'Category', type : 'text' },
                    { key : 'data_sub_category', val : 'Sub Category', type : 'text' },
                    { key : 'data_product_group', val : 'Product Group', type : 'text' },
                    { key : 'display', val : 'Display', type : 'text' },
                    { key : 'mrp', val : 'MRP', type : 'text' },
                    { key : 'rate', val : 'Rate', type : 'text' },
                    { key : 'weight', val : 'Weight', type : 'text' },
                    { key : 'volume', val : 'Volume', type : 'text' },
                    { key : 'color', val : 'Color', type : 'text' },
                    { key : 'size', val : 'Size', type : 'text' },
                    { key : 'media_a', val : 'Media', type : 'image' },
                ],
                elements : [

                    {
                        label : 'Category ID',
                        name : 'category_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Category ID',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Category ID',
                        error : '',
                        isError : false,
                        readonly : true,
                    },

                    {
                        label : 'Sub Category ID',
                        name : 'sub_category_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Please Select Sub Category ID',
                        type : 'text',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Select Sub Category ID',
                        error : '',
                        isError : false,
                        readonly : true,
                    },

                    {
                        label : 'Product Group ID',
                        name : 'product_group_id',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Please Select Product Group ID',
                        type : 'text',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Select Product Group ID',
                        error : '',
                        isError : false,
                        readonly : true,
                    },

                    {
                        label : 'Display',
                        name : 'display',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [
                            { key : 'Select Display', value : '' },
                            { key : 'Show', value : 'Show' },
                            { key : 'Hide', value : 'Hide' },
                        ],
                        placeholder : 'Please Select Display',
                        type : 'select',
                        validation : 'required',
                        class : 'col-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 mb-3',
                        labelClass : '',
                        hint : 'Please Select Display',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'MRP',
                        name : 'mrp',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter MRP',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter MRP',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Rate',
                        name : 'rate',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Rate',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Rate',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Cost',
                        name : 'cost',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Cost',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Cost',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Tax',
                        name : 'tax',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Tax',
                        type : 'text',
                        validation : 'required | string',
                        class : 'col-12 col-sm-12 col-md-3 col-lg-3 col-xl-3 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Tax',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                    {
                        label : 'Itemcode',
                        name : 'itemcode',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Itemcode',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Itemcode',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Barcode',
                        name : 'barcode',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Barcode',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Barcode',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Weight in Grams',
                        name : 'weight',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Weight',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Weight',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Volume in Mili Gram',
                        name : 'volume',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Volume',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Volume',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Color Hex Code',
                        name : 'color',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Color',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Color',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Size',
                        name : 'size',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Enter Size',
                        type : 'text',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-2 col-lg-2 col-xl-2 mb-3',
                        labelClass : '',
                        hint : 'Please Enter Size',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media A',
                        name : 'media_a',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media A',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media A is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media B',
                        name : 'media_b',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media B',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media B is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media C',
                        name : 'media_c',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media C',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media C is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media D',
                        name : 'media_d',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media D',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media D is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media E',
                        name : 'media_e',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media E',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media E is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },
                    {
                        label : 'Sub Media F',
                        name : 'media_f',
                        value : '',
                        values : [],
                        ObjectValue : {},
                        options : [],
                        placeholder : 'Select Sub Media F',
                        type : 'image',
                        validation : '',
                        class : 'col-12 col-sm-12 col-md-12 col-lg-12 col-xl-12 mb-3',
                        labelClass : '',
                        hint : 'Sub Media F is Required',
                        error : '',
                        isError : false,
                        readonly : false,
                    },

                ],
            },
        }
    },

    methods : {

        change(e){
            /* console.log(e.target.value); */
            this.formData.elements[0].value = this.product_group.category_id;
            this.formData.elements[1].value = this.product_group.sub_category_id;
            this.formData.elements[2].value = this.product_group.id;
        },

        /* getBusinessPlan(){
            window.axios.get('/auth/crud/showall?model=BusinessPlan&key=plan_name&val=id').then(res => {
                this.formData.elements[1].options = res.data;
            });
        } */
    },

    created(){
        if(this.id == null){
            this.formData.id = 0;
        } else {
            this.formData.id = this.id;
        }
    },

    mounted() {
    },

}
</script>
